ifdef CONFIG_ONEPLUS3_BLD
dts-dirs += 15801_DVT
dts-dirs += 15801_PVT
else ifdef CONFIG_ONEPLUS3T_BLD
dts-dirs += 15811_PVT
dts-dirs += 15811_PVT2
dts-dirs += 15811_PVT3
endif

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
